import { Ticker as ITicker } from "@trading-dashboard/shared";

export const INITIAL_TICKERS: ITicker[] = [
  {
    id: "AAPL",
    symbol: "AAPL",
    name: "Apple Inc.",
    currentPrice: 185.5,
    change: 0,
    changePercent: 0,
    volume: 50000000,
    lastUpdate: new Date(),
  },
  {
    id: "TSLA",
    symbol: "TSLA",
    name: "Tesla, Inc.",
    currentPrice: 242.8,
    change: 0,
    changePercent: 0,
    volume: 120000000,
    lastUpdate: new Date(),
  },
  {
    id: "BTCUSD",
    symbol: "BTC/USD",
    name: "Bitcoin",
    currentPrice: 43250.0,
    change: 0,
    changePercent: 0,
    volume: 25000000000,
    lastUpdate: new Date(),
  },
  {
    id: "GOOGL",
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    currentPrice: 140.25,
    change: 0,
    changePercent: 0,
    volume: 28000000,
    lastUpdate: new Date(),
  },
  {
    id: "AMZN",
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    currentPrice: 151.75,
    change: 0,
    changePercent: 0,
    volume: 45000000,
    lastUpdate: new Date(),
  },
];
